# Generated by Django 3.1 on 2020-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20200612_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_money',
        ),
    ]
